language: python
python:
    - "2.7"
virtualenv:
    # Use the libraries installed via apt-get
    # See https://groups.google.com/forum/?fromgroups=#!topic/travis-ci/GItMjyExDPY
    system_site_packages: true
install:
    ## The following is a dependency of python-scipy
    #- sudo apt-get install python-numpy
    - sudo apt-get install python-scipy
script: 
    python setup.py test
